### ISSUE TITLE
[DOCS] Provide helpful error message when dds is invoked without the -t option

### ISSUE THREAD

**Issue by traversaro** [vector-of-bool/dds#10]
I tried to run `dds build` in a dds project, and I got the following error: 
~~~
[22:25:56] [critical] Reading file: /home/straversaro/src/dds-playground/dds/toolchain.dds: No such file or directory
~~~

If I understood well the spirit of the "Offering a Helping Hand" section in https://vector-of-bool.github.io/2020/01/06/new-decade.html , it would be great if the error included a reference to the documentation on the `-t` option to specify the toolchain to use.

**Comment by vector-of-bool** [comment]
Oops. I must have missed that one. I'll get this one in the next release.

**Comment by traversaro** [comment]
Thanks a lot!
