### ISSUE TITLE
[BUG] (beta.1) `bpt pkg create` fails badly if output file is a directory

### ISSUE THREAD

**Issue by maxtruxa** [vector-of-bool/dds#125]
**Steps to Reproduce**

```sh
bpt new repro --dir=repro --split-src-include=false
cd repro
mkdir dist
bpt pkg create --out=dist --if-exists=replace
```

**`bpt` Output**

```
[info ] sdist: Export library from /home/ANONYMIZED/repro
[critical] An unhandled std::system_error arose. THIS IS A BPT BUG! Info: leaf::verbose_diagnostic_info for Error ID = 1
Exception dynamic type: std::__ios_failure
std::exception::what(): basic_ios::clear: iostream error:
Unhandled error objects:
[with Name = bpt::cli::pkg_subcommand]: 1
[with Name = bpt::cli::subcommand]: 4

[critical] Exception message from std::system_error: iostream error
```

**Desktop:**

- Operating System: Linux
- Compiler: n/a
- `bpt` Version: `1.0.0-beta.1` (4650bbce6991a37c034a161c670b42056405286a)

**Additional context**

The error originates from [this call to `neo::compress_directory_targz`](https://github.com/vector-of-bool/dds/blob/4650bbce6991a37c034a161c670b42056405286a/src/bpt/sdist/dist.cpp#L99) because it can't call `std::ofstream::open()` on an existing directory.

**Comment by vector-of-bool** [comment]
Thank you for the detailed bug report and PR!

This is fixed by #126
