### ISSUE TITLE
[TWEAK] DDS file extension conflicts with DirectDraw Surface

### ISSUE THREAD

**Issue by AnotherFoxGuy** [vector-of-bool/dds#2]
The DDS filename extension is already being used by the [DirectDraw Surface format](https://en.wikipedia.org/wiki/DirectDraw_Surface).
This causes on windows that the files are being marked as DDS texture files
![image](https://user-images.githubusercontent.com/9480940/70792916-8ca4c880-1d9a-11ea-8bfa-0b3667c2fe0f.png)

So maybe it would be better to choose a different filename extension so it is clearer if it is a DirectDraw Surface texture or a txt file for this

**Comment by vector-of-bool** [comment]
The file format itself is identical to the format specified by libman (as discussed in #14), so a better extension may be `.lm`, which isn't yet used AFAICT?

**Comment by vector-of-bool** [comment]
I'm going to close this issue and defer to #14.
