### ISSUE TITLE
[FEATURE] Cache warnings on disk to be re-displayed on re-running the build

### ISSUE THREAD

**Issue by Quincunx271** [vector-of-bool/dds#26]
**Describe the scenario and circumstances that should be addressed**

After compiling a file, any emitted warnings are not saved. This means that the next compile will not display the warning unless the file is recompiled. Although perhaps the user _should_ fix the warnings before they disappear, sometimes the warnings are missed and the code is presumed to be warning free despite it very much not being so.

**Describe alternatives you've considered**

Many people tout this as the reason to use `-Werror`: if a warning stops the build, it's impossible to forget to address it. However, I disagree with `-Werror` for this purpose. Yes, warnings should be addressed. But sometimes, ephemeral warnings come up in the process of natural development, such as with unused variables. Halting the thought process to address the warning right away is undesirable. Warnings should be addressed, but they don't need to interrupt the programmer.

Forcing the programmer to address the warning right away can easily lead to `(void)variable;` committed and living forever. The variable never became used, but now the warning is hidden, and the programmer forgot to remove it.

`-Werror` can catch this mistake in CI, but it would be preferable to catch it before then.

**Describe the solution you'd like**

My ideal build system would cache the warnings generated by the compiler, emitting the warnings even if the file is not recompiled.

There is some nuance here, however. Sometimes, the sheer amount of false-positive warnings drowns out useful warnings, especially when using experimental implementations of new language features. In these cases, it may be reasonable to turn off re-emitting of warnings, perhaps simply saying "N warnings generated" instead.

**Additional context**

Perhaps relevant: Rust's [cargo was recently changed](https://github.com/rust-lang/cargo/blob/master/CHANGELOG.md#cargo-140-2019-12-19) to do exactly this:

> Compiler warnings are now cached on disk. If a build generates warnings, re-running the build will now re-display the warnings.

**Comment by vector-of-bool** [comment]
This was actually a feature I've wanted to add but haven't gotten around to creating a ticket for.

I'm actually hoping to rework the caching system to be far more powerful than it currently is. In a system where we like to "rebuild the world," caching the outputs of the build process is paramount. Amongst those cache items should be compiler warnings and messages.

The current "cache" is done in the same manner as Ninja/Make: Just check timestamps. Of course, when a file disappears, we fall-through and we'd have to rely on `ccache`, which is almost as good but still not as fast as we _could_ be, plus it doesn't play nice with MSVC.

**Comment by vector-of-bool** [comment]
It's been many moons, but this is going to be in the next (and final) alpha release. Compiler output from prior compilations on unchanged files in the main project will be re-printed when a build is executed (with a note).
