### ISSUE TITLE
[DOCS] Tutorial on consuming dependencies

### ISSUE THREAD

**Issue by Quincunx271** [vector-of-bool/dds#27]
**Describe the desired documentation change**

I've read the docs on source distributions, the local package repository, the package catalog, and library and package dependencies. Despite this, I can't seem to wrap my head around how dds expects me to do package management.

Can we get a tutorial which uses a dependency? For example, a Hello World using fmt.

**Comment by vector-of-bool** [comment]
I'm tentative to wait until I have a better story around package catalog management than it currently is. The current process involves a lot of manual poking, and it would be great to replace that with automated catalog management.
