### ISSUE TITLE
[FEATURE] Replace `test_driver` with a generic solution

### ISSUE THREAD

**Issue by vector-of-bool** [vector-of-bool/dds#48]
**Describe the scenario and circumstances that should be addressed**

`dds` gives special privilege to a "test-driver" library, which is currently only Catch2, and only the version that it ships. The way it links and uses the test-driver is also convoluted and slows the build.

**Describe the solution you'd like**

Allow a "test_uses" and "test_depends" so that a project can declare libraries that should be only available to tests, and do not act as transitive dependencies for its dependees.

**Additional context**

This will require that `dds` is able to load a different set of usage requirements for its `.test.c[pp]` files than for the other compiled files.

**Comment by Quincunx271** [comment]
Can you assign me this?
