### ISSUE TITLE
[BUG] Compilation fails with a large number of source files.

### ISSUE THREAD

**Issue by thevisus** [vector-of-bool/dds#60]
## Description

Compilation fails if `dds` builds more than `N` source files at once, where `N` is the current resource limit as determined by `ulimit`, `sysctl` , or similar.

# Steps to Reproduce

A couple ways to trigger this error...

1. Artificially decrease soft limit and then `build`:
```sh
ulimit -S -n $REALLY_SMALL_NUMBER
dds build ...
```

2. Define a library/package that depends on & uses many other libraries and then do a clean build.

## `dds` Output
```
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: cannot get current path: Too many open files
```

## System / platform
 - Operating System: macOS, Linux
 - Compiler: GCC
 - `dds` Version: `0.1.0-alpha.6`

## Additional context
Performing `build` within a clean package root that exhibits this error will fail repeatedly. i.e. `dds` starts building file `1/X` (where `X` = num source files) on each and every run.
If `build` is issued after `n/X` object files already exist (where `1 < n < X`), then `dds` starts building file `n + 1` and it's sometimes possible to complete successfully - depending on whether `X - n < L` (`L` = resource limit).

## Known workaround
Adjusting the resource limits for the process enables successful builds.

e.g. for environments using `ulimit`:
```sh
ulimit -S -n $SUFFICIENTLY_LARGE_NUMBER
```

**Comment by vector-of-bool** [comment]
I'm not sure if we can recover from a low file limit, but we can certainly display a more helpful error message.

**Comment by thevisus** [comment]
I agree and honestly wouldn't expect that. To clarify, though, this is happening when building 280+ files from a single run of `dds build` (which is building about a dozen packages into the app `elf` file). I thought it was odd that so many files **remained** open, even well after all source files for the containing lib/pkg were successfully built. Even with a ulimit of ~350 the build bails on the linker step. The host needs >400 ulimit to build from scratch.

Is this by design in how the build plan is executed? (i.e. some sort of parallel build: partition per package, sync at linker phase) Or is it possible that file descriptors are leaking somewhere?

**Comment by vector-of-bool** [comment]
It's possible that there are some fd leaks, yeah. Nothing I can think of should be holding open that many file descriptors at once. I will take a closer look and add a pathological test case with thousands of files to see if I can reproduce the issue.

**Comment by Dox5** [comment]
I've started to take a look at this, I've created a test project with a simple setup of 100 pairs of hpp + cpp files (and a single main). Without the extra restrictive ulimit I can build the project as expected. Setting the ulimit down to 128 causes the issues described - although I'm using GCC11 and I think this might have caused the errors to change. I'm able to reproduce with a clean build from develop (b35d87245e8174506df780fd9fe112d89351a85b) as well.

I've run DDS using strace and analysed the output for missing closes - it seems like it's a pipe that is not being correctly cleared up. This example is from one thread but each thread appears to be leaking around 20 handles
```
7 leaked from Event(tid=0, timestamp='14:24:47.748402', op='pipe', result=0, args='[7, 13]')
8 leaked from Event(tid=0, timestamp='14:24:47.808773', op='pipe', result=0, args='[8, 10]')
16 leaked from Event(tid=0, timestamp='14:24:47.859744', op='pipe', result=0, args='[16, 17]')
23 leaked from Event(tid=0, timestamp='14:24:47.936511', op='pipe', result=0, args='[23, 24]')
29 leaked from Event(tid=0, timestamp='14:24:48.010683', op='pipe', result=0, args='[29, 30]')
34 leaked from Event(tid=0, timestamp='14:24:48.065734', op='pipe', result=0, args='[34, 35]')
40 leaked from Event(tid=0, timestamp='14:24:48.135131', op='pipe', result=0, args='[40, 41]')
46 leaked from Event(tid=0, timestamp='14:24:48.207032', op='pipe', result=0, args='[46, 47]')
52 leaked from Event(tid=0, timestamp='14:24:48.257921', op='pipe', result=0, args='[52, 53]')
57 leaked from Event(tid=0, timestamp='14:24:48.314196', op='pipe', result=0, args='[57, 58]')
61 leaked from Event(tid=0, timestamp='14:24:48.376505', op='pipe', result=0, args='[61, 62]')
68 leaked from Event(tid=0, timestamp='14:24:48.434580', op='pipe', result=0, args='[68, 69]')
74 leaked from Event(tid=0, timestamp='14:24:48.515352', op='pipe', result=0, args='[74, 75]')
80 leaked from Event(tid=0, timestamp='14:24:48.581683', op='pipe', result=0, args='[80, 81]')
85 leaked from Event(tid=0, timestamp='14:24:48.638905', op='pipe', result=0, args='[85, 86]')
92 leaked from Event(tid=0, timestamp='14:24:48.705641', op='pipe', result=0, args='[92, 93]')
97 leaked from Event(tid=0, timestamp='14:24:48.769673', op='pipe', result=0, args='[97, 99]')
102 leaked from Event(tid=0, timestamp='14:24:48.822816', op='pipe', result=0, args='[102, 103]')
111 leaked from Event(tid=0, timestamp='14:24:48.891097', op='pipe', result=0, args='[111, 113]')
113 leaked from Event(tid=0, timestamp='14:24:48.928855', op='pipe', result=0, args='[113, 114]')
121 leaked from Event(tid=0, timestamp='14:24:48.973901', op='pipe', result=0, args='[121, 122]')
```
which from the docs appears to be the read end of the pipe being created. I'll go and find where in DDS that pipe is created (I expect for some tool invocation?) and trace it in code next

bit's and pieces:
```bash
# Generate a project with a bunch of dummy files
for N in $(seq 1 100) ; do  echo -e "int a_function_$N();\n" > "a_file_$N.hpp" ; echo -e "int a_function_$N() { return $N; }\n" > "a_file_$N.cpp" ; done
```

```bash
# Run strace and then filter out non-dds invocations
rm -r _build/ ; rm trace-files/* ; strace -tt -ff --output=trace-files/tid ~/Documents/dds/_build/dds build -t :gcc

# Split between dds traces and compiler/linker/tools traces (assuming they all live in /usr!)
pushd trace-files ; grep -lF 'execve("/usr' * | xargs -I{} mv {} compiler.{} ; popd
```

This uses the strace output to line up opens & closes
```python3
#! /usr/bin/env python3

import sys
import pathlib

from collections import namedtuple

def handle_openat(open_set, event):
    if(event.result in open_set):
        print(f"Eek openat opened an already in use handle: {event.result}")

    open_set[event.result] = event
    return open_set

def handle_pipe(open_set, event):
    fds = ("".join([x for x in event.args if x not in "[],"])).split(" ")
    for fd in fds:
        if(fd in open_set):
            print(f"Eek pipe opened an already in use handle: {fd}")

        open_set[int(fd)] = event
    return open_set

def handle_close(open_set, event):
    try:
        del open_set[int(event.args)]
    except KeyError:
        print(f"Eek - closed handled {event.args} but it wasn't open")
    return open_set

handlers = {
    "openat": handle_openat,
    "pipe": handle_pipe,
    "close": handle_close,
}

Event = namedtuple("Event", ["tid", "timestamp", "op", "result", "args"])

def parse_event(event_str, tid):
    ts, event = event_str.split(sep=" ", maxsplit=1)
    op, _ = event.split("(", maxsplit=1)
    _, result = event.rsplit("=", maxsplit=1)
    args_begin, args_end = event.index("("), event.rindex(")")
    return Event(tid, ts, op, int(result.strip()), event[args_begin+1:args_end])

events = []

for tracefile in sys.argv[1:]:
    tracefile = pathlib.Path(tracefile)

    open_fds = dict()

    print(f"{tracefile}")

    with tracefile.open("r") as trace:
        for line in trace:
            try:
                event = parse_event(line.strip(), 0)
                handler = handlers[event.op]
                open_fds = handler(open_fds, event)
            except ValueError:
                #print(f"line '{line}' failed to parse\n")
                continue
            except KeyError:
                continue

    if(len(open_fds) > 0):
        print(f"{tracefile} had {len(open_fds)} open filehandles")
        for fd, source_event in open_fds.items():
            print(f"{fd} leaked from {source_event}")
```

**Comment by Dox5** [comment]
I think I've got to the bottom of this (on *nix systems at least!). I've raised #105 that ensures that the read side of the pipe created when tools are invoked is closed once no longer needed. I've tested with the project I had that was previously failing and that now compiles successfully from a clean build
