### ISSUE TITLE
[BUG] `dds repoman ls` segfaults

### ISSUE THREAD

**Issue by Quincunx271** [vector-of-bool/dds#73]
**Describe the bug**

`dds repoman ls <directory>` segfaults rather than printing the contents of the repository.

**Steps to Reproduce**

```
dds repoman init asdf
dds repoman ls asdf
```

**`dds` Output**

```
Segmentation fault (core dumped)
```

**Desktop (please complete the following information):**

 - Operating System: Ubuntu 20.04
 - `dds` Version: `0.1.0-alpha.6` and `develop`

**Comment by vector-of-bool** [comment]
It seems that the segfault only occurs when `dds` is compiled with the `-Os` flag. In development, I'm not seeing this, as it seems enabling sanitizers are causing the issue to disappear. If I compile/link without `-Os` and without sanitizers, I get an assertion failure around the site of the segfault instead.

This appears to actually be an issue in `all_packages()`. It returns a view that contains a reference to a local variable. A simple enough fix, though.
